### ISSUE TITLE
Generated lua function can't finish successfully

### ISSUE THREAD

**Issue by tjpalmer** [temperlang/temper#100]
This temper code:

```ts
let hi(ncols: Int, length: Int): Int | Bubble {
  if (length % ncols != 0) { bubble() }
  length / ncols
}
```

Translates to this in lua:

```lua
hi = function(ncols__2, length__3)
  local return__0, t_0, local_1, local_2, local_3, local_9, local_10, local_11;
  ::continue_1::local_1, local_2, local_3 = temper.pcall(function()
    t_0 = temper.imod(length__3, ncols__2);
  end);
  if local_1 then
  else
    goto break_0;
  end
  if (t_0 ~= 0.0) then
    local local_5, local_6, local_7;
    local_5, local_6, local_7 = temper.pcall(function()
      temper.bubble();
    end);
    if local_5 then
    else
      goto break_0;
    end
  end
  local_9, local_10, local_11 = temper.pcall(function()
    return__0 = temper.idiv(length__3, ncols__2);
    return return__0, 'return';
  end);
  if local_9 then
  end
  ::break_0::temper.bubble();
end;
```

But all paths eventually lead to that final bubble. I suspect something else ought to happen in the `if local_9` block.

This is boiled down from larger code that works in the other backends.

**Comment by tjpalmer** [comment]
> I think the same issue is showing up with the generated Lua for the new functions/local* tests.

That does look similar. On my new branch, I've already added a some code to a funtest for this case also, and I'm planning to dig into it either today or Monday.

Have you started looking into causes/fixes yet on your end?

**Comment by ben-509** [comment]
Not yet... I ran it through a debugger to find the hang, and once I confirmed it's not related to local functions, I wanted to note that here and get back to adding some tests and such to the PR.

**Comment by tjpalmer** [comment]
Sounds good. I'll work it from my end, then.

**Comment by tjpalmer** [comment]
I think it's possible his relates to #101 because both involve if statements. No guarantee because they're very different in other ways, but it doesn't seem impossible.

**Comment by tjpalmer** [comment]
Just got #101 fixed on my branch, although with some efficiency concerns, and it doesn't fix this one here, so definitely different issues.

**Comment by ShawSumma** [comment]
It looks to me that when a `temper.pcall` ends with a `return`, it fails to add the return to the list of things it should check for.
```
if local_9 then end
```
Is what needs to be changed to something like ```
if local_9 then
else
  if local_11 == 'return' then
    return local_10
  end
end```

There is labelsUsed and usedLabels for this. But `"return"` never gets added to either in this case, oddly.
