### ISSUE TITLE
Lua loses match cases

### ISSUE THREAD

**Issue by tjpalmer** [temperlang/temper#101]
For this temper source:

```ts
export let hi(a: Int, b: Int): Int {
  match (a) {
    0 -> match (b) {
      0 -> 1;
      1 -> 2;
      2 -> 3;
      else -> 0;
    }
    1 -> 11;
    2 -> 22;
    3 -> 33;
    else -> 0;
  }
}
```

Lua loses all but the first 2 and the last/`else` match cases:

```lua
hi = function(a__2, b__3)
  local return__0;
  if (a__2 == 0.0) then
    if (b__3 == 0.0) then
      return__0 = 1.0;
    elseif (b__3 == 1.0) then
      return__0 = 2.0;
    else
      return__0 = 0.0;
    end
  elseif (a__2 == 1.0) then
    return__0 = 11.0;
  else
    return__0 = 0.0;
  end
  return return__0;
end;
```

Other backends have them all:

```py
def hi(a__2: 'int1', b__3: 'int1') -> 'int1':
  return__0: 'int1'
  if a__2 == 0:
    if b__3 == 0:
      return__0 = 1
    elif b__3 == 1:
      return__0 = 2
    elif b__3 == 2:
      return__0 = 3
    else:
      return__0 = 0
  elif a__2 == 1:
    return__0 = 11
  elif a__2 == 2:
    return__0 = 22
  elif a__2 == 3:
    return__0 = 33
  else:
    return__0 = 0
  return return__0
```

**Comment by tjpalmer** [comment]
The issue was with recursive rewrites of elseifs up the chain. Existing elseifs were being discarded. These should be exercised extensively in regex.temper.md, but I think be-lua might be entirely circumventing generated std code. That's one possible explanation for why we may not have caught this before.

The current Lua implementation also requires O(n^2) tree copying in the length of elseif chains. I haven't tried to reorg the code yet on my branch, but doing something more like be-py's elif processing might be better.

**Comment by ShawSumma** [comment]
This seems like something that having a utility to handle (like "elif-y") would be useful, both Lua and Py need stuff like this.

**Comment by tjpalmer** [comment]
> This seems like something that having a utility to handle (like "elif-y") would be useful. As you said, both Lua and Py need stuff like this.

Good point. I'll probably hack it for now, but yeah, having a tmpl option to help is a good idea.
