### ISSUE TITLE
Lua Backend could blow through 200 locals easily

### ISSUE THREAD

**Issue by ShawSumma** [temperlang/temper#13]
Most Lua implementations has a limit of about 200 registers per function (args + locals + stack).

As temper makes heavy use of locals for efficiency, it is highly likely that the limit of 200 will be reached soon.

Consider putting some locals in a table according to some heuristic.

**Comment by tjpalmer** [comment]
@ShawSumma Is this fixed?

**Comment by ShawSumma** [comment]
This has been fixed, if there are too many locals it creates a table to use.
