### ISSUE TITLE
GIthub workflow for jre4temper repo

### ISSUE THREAD

**Issue by ben-509** [temperlang/temper#132]
Laying out some requirements:

- [This comment][steps] summarizes the steps to build a JRE release.
  - It's a gradle task, so nothing complicated there.
- Then those assets need to be saved somewhere
  - The [jre4temper][] repo is set up to accept releases.
- The release-dev workflow needs to pick up the appropriate assets.
  - Right now it's a `wget` with some environment variables.
  - Seems like we could simply add a manifest to the assets.
- The release-dev workflow needs to configure its test matrix.
  - We can use [outputs from a prior job][matrix] to configure it. ([Example][dynamic-matrix])
  - Thus our manifest can also configure the matrix.

[steps]: https://github.com/temperlang/temper/issues/120#issuecomment-2096809477
[jre4temper]: https://github.com/temperlang/jre4temper
[matrix]: https://stackoverflow.com/questions/65056670/is-it-possible-to-have-a-dynamic-strategy-matrix-in-a-workflow-in-github-actions
[dynamic-matrix]: https://github.com/marketplace/actions/dynamic-matrix#examples

**Comment by ben-509** [comment]
As to running it, if we have a monthly job that finds the latest minor versions of JREs using `sdkman` or something like that, it'd be fine. 

Another point to test out: The prebake will need to run on various runners, each of which generates local artifacts. Then a combiner job pulls those together, builds a manifest, and plonks it all in `jre4temper`.

**Comment by tjpalmer** [comment]
@ben-509 Is this issue done?
