### ISSUE TITLE
REPL misses leading Exclamation Point only sometimes.

### ISSUE THREAD

**Issue by ShawSumma** [temperlang/temper#154]
Found a bug while reporting a bug.

The REPL does not like leading `!`.

This is usually fine, but i wanted to translate to python... so i need my not.

Here's an [Asciinema of The Incident](https://asciinema.org/a/qplvL4b0UTvK6g1R1kYwXiO3I).

**Comment by tjpalmer** [comment]
Tried it out. Looks like it's doing a "repeat previous like starting with this prefix thing". But maybe only for lines starting with letters or something?

Yeah, I agree we should disable that apparently automatic feature.
