### ISSUE TITLE
Top-level library exports

### ISSUE THREAD

**Issue by tjpalmer** [temperlang/temper#19]
It would be nice to be able to say `import { whatever } from "there";` instead of of `import { whatever } from "there/there.js";`. Similar idea for Python. Same for Temper itself, actually.

**Comment by ShawSumma** [comment]
@tjpalmer Do dir modules fix this?

**Comment by tjpalmer** [comment]
> @tjpalmer Do dir modules fix this?

They actually do. We could either close this now, or we can wait until more of the supporting functionality is done.

**Comment by tjpalmer** [comment]
About to update the tutorial for dir modules. But I think I still want to remove stopgap merge-all functionality before closing this.

**Comment by tjpalmer** [comment]
I'm going to close this after all. The stopgap is only there when a top-level module is missing, so that doesn't really matter for common use cases.
