### ISSUE TITLE
Lua backend writes files wrong.

### ISSUE THREAD

**Issue by ShawSumma** [temperlang/temper#53]
The Lua backend sometimes writes the files wrong. 

Often it has to do with lines 3-5 being replaced with the last 2 lines of the file.

I'm not too sure what causes it or how to go about fixing it.

**Comment by mikesamuel** [comment]
Are there multiple *FileSpecifications* with the same name?

**Comment by ShawSumma** [comment]
Yes that was very much it, patches are in the works.

**Comment by tjpalmer** [comment]
@ShawSumma Is this fixed now?
