### ISSUE TITLE
Lost var assignment in tmpl

### ISSUE THREAD

**Issue by tjpalmer** [temperlang/temper#93]
The assignment to null goes out of order here, and note the that behavior is correct in the interpreter:

```ts
$ do {
    class A {}
    var x: A | Null = new A();
    console.log(do { x.as<A>(); "A" } orelse "null");
    x = null;
    do { x.as<A>(); "A" } orelse "null"
  }
A
interactive#0: "null"
$ translate(0, "js")
Translated js for interactive#0
  interactive-0000/
    chunk.js: text/javascript
      import {
        requireInstanceOf as requireInstanceOf__5, globalConsole as vGlobalConsole__47_6
      } from "@temperlang/core";
      /** @type {string} */
      let return_0;
      /** @type {string} */
      let t_1;
      class A_2 {
        constructor() {
          return;
        }
      }
      /** @type {A_2 | null} */
      let x_3 = null;
      /** @type {A_2 | null} */
      let t_4 = new A_2();
      x_3 = t_4;
      try {
        requireInstanceOf__5(x_3, A_2);
        t_1 = "A";
      } catch {
        t_1 = "null";
      }
      vGlobalConsole__47_6.log(t_1);
      try {
        requireInstanceOf__5(x_3, A_2);
        return_0 = "A";
      } catch {
        return_0 = "null";
      }
      export default return_0;
    chunk.js.map: application/json
      { "version": 3, "file": "js/interactive-⋯M,AAAN,OAAM;AAAA,CAAA;AACpC,eAAAA,QAAA" }
interactive#1: void
```

**Comment by tjpalmer** [comment]
I'll try looking into this some.

**Comment by mikesamuel** [comment]
Odd.  Would you like me to figure out why that isn't happening?

**Comment by mikesamuel** [comment]
I wonder if it's something to do with how we produce TmpLControlFlow.CombinedDeclarations

**Comment by tjpalmer** [comment]
But yeah, seems to be in `fixupBlockContent` and I think that appearance of ` = null` on the declaration is related. I wasn't sure earlier if that was spurious.

**Comment by tjpalmer** [comment]
Yeah, seems `fixupBlockContent` looks only at declarations when seeing if it can move the assignment into the declaration. Probably need full recursive sweep looking for any mentions at all between assignment and declaration.

**Comment by tjpalmer** [comment]
Maybe should just avoid combining on any spurious content other than declarations even.

**Comment by tjpalmer** [comment]
@mikesamuel I requested your review for a very small PR that seems to fix this issue well enough for now. I suspect it could be optimized more in the future, or maybe there are new breakages that my simple fix causes that we just don't test for. Anyway, if you could give it a look, that would be great. Thanks!
